version: '3'
services:
    db:
        image: dolthub/dolt-sql-server
        ports:
        - 3306
        volumes:
        - ./db/sql:/docker-entrypoint-initdb.d
    py-srv:
        build: py-srv
        command: python app.py
        ports:
        - 443:443
    py-test-srv:
        build:
            context: py-test-srv
        command: sh -c "/wait && python app.py"
        environment:
        - WAIT_HOSTS=db:3306,py-srv:443
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
        depends_on:
        - py-srv
        links:
        - py-srv:py-srv
